# Generated by Django 5.0.6 on 2026-03-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_user_id_a53e17_idx',
            old_name='tasks_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_user_id_e06a45_idx',
            old_name='tasks_user_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_user_id_20dbf7_idx',
            old_name='tasks_user_due_date_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_created_db4e37_idx',
            old_name='tasks_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='taskhistory',
            new_name='task_histor_task_id_7a1259_idx',
            old_name='history_task_action_idx',
        ),
        migrations.RenameIndex(
            model_name='taskhistory',
            new_name='task_histor_timesta_cb931b_idx',
            old_name='history_timestamp_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
